prometheus:
  prometheusSpec:
    additionalAlertManagerConfigs:
      - static_configs:
        - targets: 
          - "myprom-kube-prometheus-sta-alertmanager:9093"
    externalUrl: http://localhost/prometheus
    routePrefix: /prometheus
additionalPrometheusRulesMap:
  rule-name:
    groups:
      - name: ruleset_1
        rules:
          - alert: HighErrorRate
            expr: total_predictions_total - correct_predictions_total > 10
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: HighErrorRate
              description: "HighErrorRate"
alertmanager:
  config:
    global:
      smtp_smarthost: 'smtp.office365.com:587'
      smtp_from: 'relma23team12@outlook.com'
      smtp_auth_username: 'relma23team12@outlook.com'
      smtp_auth_password: 'HighErrorRate'
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'team-emails'
      routes:
      - match:
          alertname: HighErrorRate
        receiver: 'team-emails'
    receivers:
    - name: 'team-emails'
      email_configs:
      - to: 'relma23team12@outlook.com'
        send_resolved: true

