replicaCount: 1
image:
  repository: ghcr.io/remla23-team12/app
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  path: /
modelService:
  url: http://flask-container-2-service:8082
