apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-container-1-depl
  labels:
    app: flask-container-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-container-1
  template:
    metadata:
      labels:
        app: flask-container-1
    spec:
      containers:
      - name: flask-container-1
        image: {{ .Values.flaskContainer1.image }}
        ports:
        - containerPort: {{ .Values.flaskContainer1.port }}
        env:
        - name: MODEL_SERVICE_URL
          value: "http://flask-container-2-service:{{ .Values.flaskContainer2.servicePort }}"
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-container-2-depl
  labels:
    app: flask-container-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-container-2
  template:
    metadata:
      labels:
        app: flask-container-2
    spec:
      containers:
      - name: flask-container-2
        image: {{ .Values.flaskContainer2.image }}
        ports:
        - containerPort: {{ .Values.flaskContainer2.port }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
