apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-container-2-depl-experimental
  labels: {app: flask-container-2, version: experimental}
spec:
  replicas: 1
  selector:
    matchLabels: {app: flask-container-2, version: experimental}
  template:
    metadata:
      labels: {app: flask-container-2, version: experimental}
      annotations:
         prometheus.io/scrape: "true"
         prometheus.io/port: "8080"
    spec:
      containers:
      - name: flask-container-2
        image: ghcr.io/remla23-team12/model-service:0.5.0
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ghcr-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-container-1-depl-experimental
  labels: {app: flask-container-1, version: experimental}
spec:
  replicas: 1
  selector:
    matchLabels: {app: flask-container-1, version: experimental}
  template:
    metadata:
      labels: {app: flask-container-1, version: experimental}
      annotations:
         prometheus.io/scrape: "true"
         prometheus.io/port: "5000"
    spec:
      containers:
      - name: flask-container-1
        image: ghcr.io/remla23-team12/app:0.1.2
        ports:
        - containerPort: 5000
        env:
        - name: MODEL_SERVICE_URL
          value: "http://flask-container-2-service:8082"
      imagePullSecrets:
      - name: ghcr-credentials
---