apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: flask-container-1-service
            port:
              number: {{ .Values.flaskContainer1.servicePort }}
      - pathType: Prefix
        path: "/prometheus"
        backend:
          service:
            name: myprom-kube-prometheus-sta-prometheus
            port:
              number: 9090
