apiVersion: v1
kind: Service
metadata:
  name: flask-container-1-service
spec:
  selector:
    app: flask-container-1
  ports:
    - protocol: TCP
      port: {{ .Values.flaskContainer1.servicePort }}
      targetPort: {{ .Values.flaskContainer1.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-container-2-service
spec:
  selector:
    app: flask-container-2
  ports:
    - protocol: TCP
      port: {{ .Values.flaskContainer2.servicePort }}
      targetPort: {{ .Values.flaskContainer2.port }}